
[workspace]
members = [
    "ex1",
    "structs-area0",
    "control_flow",
    "match_ex",
    "options-division",
    "enums-keyboard",
    "enum-areacalc",
    "struct-areacalc",

]
resolver = "2"